### PR TITLE
Add release and Changelog entry for 0.0.4

### PR DESCRIPTION
**Pull request by syncrou**

### CODE REVIEW

**Review by lindgrenj6 — APPROVED** [review]

**Review by roliveri — APPROVED** [review]

**Comment by slemrmartin** [comment]
@syncrou publishing failed https://github.com/slemrmartin/receptor_controller-client-ruby/actions/runs/204030792

**Comment by slemrmartin** [comment]
Hm, interesting this was merged 7 days ago.

**Comment by lindgrenj6** [comment]
Yes that will fail for your local - it worked for this repo.

**Comment by lindgrenj6** [comment]
It ran when you rebased/pushed.

**Pull request merged**
